SIM ?= icarus
TOPLEVEL_LANG ?= verilog

VERILOG_INCLUDE_DIRS += \
$(PWD)/ \
$(PWD)/../../lib/hw/lsi/cores/rtclock/hdl/ \
$(PWD)/../../lib/hw/lsi/cores/traffic_analyzer_gmii/hdl/ \
$(PWD)/../../lib/hw/lsi/cores/traffic_generator_gmii/hdl/  \
$(PWD)/../../lib/hw/lsi/cores/filter_gmii/hdl/  \
$(PWD)/../../lib/hw/lsi/common/hdl

VERILOG_SOURCES += \
$(PWD)/../../lib/hw/lsi/cores/rtclock/hdl/rtclock.v \
$(PWD)/../../lib/hw/lsi/cores/traffic_generator_gmii/hdl/traffic_generator_gmii_cpu_regs_defines.v \
$(PWD)/../../lib/hw/lsi/cores/traffic_generator_gmii/hdl/traffic_generator_gmii_cpu_regs.v \
$(PWD)/../../lib/hw/lsi/cores/common/hdl/ethernet_crc_8.v \
$(PWD)/../../lib/hw/lsi/cores/traffic_analyzer_gmii/hdl/ethernet_crc_8_check.v \
$(PWD)/../../lib/hw/lsi/cores/traffic_generator_gmii/hdl/traffic_generator_gmii.v \
$(PWD)/../../lib/hw/lsi/cores/traffic_analyzer_gmii/hdl/traffic_analyzer_gmii_cpu_regs_defines.v \
$(PWD)/../../lib/hw/lsi/cores/traffic_analyzer_gmii/hdl/traffic_analyzer_gmii_cpu_regs.v \
$(PWD)/../../lib/hw/lsi/cores/traffic_analyzer_gmii/hdl/traffic_analyzer_gmii.v \
$(PWD)/../../lib/hw/lsi/cores/filter_gmii/hdl/filter_gmii.v \
$(PWD)/../../lib/hw/lsi/cores/packet_mux_gmii/hdl/packet_mux_gmii.v \
$(PWD)/../../lib/hw/lsi/cores/traffic_analyzer_gmii/hdl/bram_io.v \
$(PWD)/../../lib/hw/lsi/cores/traffic_analyzer_gmii/hdl/testframe_parser.v \
$(PWD)/tester_loop.v
# use VHDL_SOURCES for VHDL files

# TOPLEVEL is the name of the toplevel module in your Verilog or VHDL file
TOPLEVEL = tester_loop

# MODULE is the basename of the Python test file
#MODULE = tb_axi_lite_flip_register
#test_my_design

# include cocotb's make rules to take care of the simulator setup
include $(shell cocotb-config --makefiles)/Makefile.sim
